### PR TITLE
the MeioUpload version 4.0 did not work so well when i wrote unit tests for the models which use MeioUpload version 4.0

### PR DESCRIPTION
**Pull request by simkimsia**
There are 3 basic issues:

1) the use of $this->settings in uploadCheckDir is definitely wrong. So I changed that to $options as expected.

2) in unit tests, the current working directory need not necessarily be WWW_ROOT. However, in uploadCheckDir, it is assumed to be the case because the code is_dir is used. So I added code which will first check if the current working directory is indeed WWW_ROOT. If not, then chdir to the assumed directory

3) in _copyFileFromTemp, there is a check on the source file whethere it is an uploaded file using the is_uploaded_file.

In unit tests, this check will surely fail. Hence I have extracted this check into a standalone entry in the $validate array.

By default, this validation is turned on. Its index is HttpPost. The validation function is uploadCheckHttpPost.

With the above changes, cake test cases can be used on Models that have MeioUpload as one of its behaviors.

In those test cases, we need a separate line of code which will turn off the validation for HttpPost.

eg a model called Image which actsAs MeioUpload under the fieldName filename

```
    $this->Image->validate['filename'] = array(
        'HttpPost' => array(
            'check' => false
        )
    ); 
```

### CODE REVIEW

**Comment by simkimsia** [comment]
I am a fan of MeioUpload.  I am also a fan of writing unit tests for the models and controllers.

I would prefer it very much that the jrbasso/MeioUpload accommodates my commits making it usable in unit tests rather than I maintain a separate fork of MeioUpload.

Thank you very much, guys.

**Comment by jrbasso** [comment]
Nice changes! Thanks so much for it. I am a little busy with others projects/company and unfortunately can't invest much time in MeioUpload, but definitely these are very good changes. Thanks!

**Comment by simkimsia** [comment]
File upload is important to me so I need this.

By the way

I made a separate f
Fork of phpthumb because the original one did not work so well with cakephp
2

Did you have any problems with the original phpthumb in cake2 ?
On Mar 25, 2012 2:59 AM, "Juan Basso" <
reply@reply.github.com>
wrote:

**Comment by jrbasso** [comment]
Unfortunately, I haven't used the MeioUpload with any CakePHP 2.x project yet.

**Pull request merged**
